name: SQL JDBC Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  build:
    strategy:
      matrix:
        java:
          - 11
          - 17
          - 21
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Build with Gradle
        run: ./gradlew build test shadowJar

      - name: Create Artifact Path
        run: |
          mkdir -p jdbc-builds
          cp ./build/libs/*.jar jdbc-builds

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jdbc-java-${{ matrix.java }}
          path: jdbc-builds
